#region COPYRIGHT
//
//     THIS IS GENERATED BY TEMPLATE
//     
//     AUTHOR  :     ROYE
//     DATE       :     2010
//
//     COPYRIGHT (C) 2010, TIANXIAHOTEL TECHNOLOGIES CO., LTD. ALL RIGHTS RESERVED.
//
#endregion

namespace System {
    /// <summary>
    /// 卫兵
    /// </summary>
    public static class Guard {
        /// <summary>
        /// 确保参数值不是NULL且不为空字符串
        /// </summary>
        public static void ArgumentNotNullOrEmptyString(string argumentValue, string argumentName) {
            ArgumentNotNull(argumentValue, argumentName);

            if (argumentValue.Length == 0) {
                throw new ArgumentException("String Cannot Be Empty", argumentName);
            }
        }

        /// <summary>
        /// 确保参数值不为NULL
        /// </summary>
        public static void ArgumentNotNull(object argumentValue, string argumentName) {
            if (argumentValue == null) {
                throw new ArgumentNullException(argumentName);
            }
        }

        /// <summary>
        /// 确保参数值不超出调用的方法所定义的允许取值范围
        /// </summary>
        public static void ArgumentOutOfRangeException<T>(string argumentName, T argumentValue, Func<T, bool> callback) {
            if (callback(argumentValue)) {
                throw new ArgumentOutOfRangeException(argumentName);
            }
        }

        /// <summary>
        /// 对执行的操作是否容错
        /// </summary>
        public static void SkipException(bool skipException, CallbackVoidHandler callback) {
            if (skipException) {
                try {
                    callback();
                }
                catch { }
            }
            else {
                callback();
            }
        }
    }
}
